### ISSUE TITLE
Note: GitHub Actions

### ISSUE THREAD

**Issue by admidori** [rp-agota/auto-build#13]
### **GitHub Actionsを利用する際の注意点**  
GitHub Actionsは、(試してみた限り)**ymlファイル上で**一回以上コマンドを実行しないとそのコマンドは使用可能にならない。  
そのため、ymlファイル内でシェルスクリプトを利用した際、シェルスクリプト内での処理に初出のコマンドが入っていた場合、それが利用可能になることは無い。  
versionや-vを使用して一度使用コマンドをymlファイル内で実行した後シェルスクリプトを使用すれば問題は無いと思われる。

**Comment by admidori** [comment]
[EX]
```
name: CI

on: 
  push: 
    branches: [ master ]
  pull_request: 
    branches: [ master ]

jobs: 
  Ubuntu: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Apt check  #ここで使用したいコマンドを実行する必要がある
        run: |
          docker version
          docker-compose version
          make -v
          gcc -v
      - name: install
        run: make install
      - name: test
        working-directory: ./.test
        run: abd src test #そうすればここで詰まらずに済む
      - name: uninstall
        run: make uninstall
```
